# This is a basic workflow to help you get started with Actions

name: Upload Datadog Data

on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 upload-dd-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: datadog/github-action-vulnerability-analysis@master
      with:
        build-file: '/pom.xml'
        service: 'petclinic2'
        version: 'v3.0'
        datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
        datadog-app-key: ${{ secrets.DATADOG_APP_KEY }}
        snyk-token: ${{ secrets.SNYK_TOKEN }}
#   runs-on: ubuntu-latest
#   steps:
#    - uses: actions/checkout@v2
#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v3
#      env:
#        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
#        DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }} 
#    - run: |-
#        npm install --save-dev @datadog/datadog-ci snyk
#        ./node_modules/.bin/snyk auth ${{ secrets.SNYK_API_TOKEN }}
#        ./node_modules/.bin/snyk test --print-deps --file=pom.xml > deps.json
#        ./node_modules/.bin/datadog-ci dependencies upload deps.json --source snyk --service petclinic2 --release-version ${{ env.version }}
