# This is a basic workflow to help you get started with Actions
#
name: GCP SetUp

on: workflow_dispatch

env:
  zone: us-central1-c
  releaseName: datadog-agent  

jobs:
  GCP-create-Kubernetes:
    
    runs-on: ubuntu-latest
    steps:
    - name: Set env ClusterName
      run: echo ::set-env name=clusterName::${{ secrets.GKE_CLUSTER_NAME}}
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        #version: '290.0.1'
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - run: gcloud container clusters create ${{secrets.GKE_CLUSTER_NAME}} --zone=${{ env.zone }}
  
  Deploy-datadog:
    needs: [GCP-create-Kubernetes]
    runs-on: ubunutu-latest
    steps:
    - name: install datadog on K8s
    # Get new cluster credentials 
    - run: |-
        gcloud container clusters get-credentials ${{secrets.GKE_CLUSTER_NAME}} --zone=${{ env.zone }}
    # Set up DataDog in Kubernetes cluster
    - run: |-
        helm repo add datadog https://helm.datadoghq.com
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
        helm install ${{ env.releaseName }} -f datadog/values.yaml  --set datadog.apiKey=${{ secrets.DATADOG_API_KEY }}
