# This is a basic workflow to help you get started with Actions
#
name: GCP SetUp

on: workflow_dispatch

jobs:
  GCP-Kubernetes:
    
    runs-on: ubuntu-latest
    steps:
    - name: Set env ClusterName
      run: echo ::set-env name=clusterName::${{ secrets.GKE_CLUSTER_NAME}}
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        #version: '290.0.1'
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - run: gcloud container clusters create ${{secrets.GKE_CLUSTER_NAME}} --zone=us-central1-c
