# This is a basic workflow to help you get started with Actions
#
name: GCP SetUp

on: workflow_dispatch

env:
  # TODO: Change registry URL if not using Docker Hub
  CONTAINER_REGISTRY_URL: https://registry.hub.docker.com

jobs:
  GCP-Kubernetes:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        #version: '290.0.1'
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - run: gcloud container clusters create test
